### ISSUE TITLE
Breaking Changes: Model Configuration and Environment Variables Update

### ISSUE THREAD

**Issue by miurla** [miurla/morphic#453]
## Changes Overview

We have made two significant changes that require user action:

1. **Model Configuration Moved to JSON**
   - All model configurations have been moved from environment variables to `public/config/models.json`
   - This includes:
     - Model IDs and names
     - Provider information
     - Tool calling configuration
     - Model status (enabled/disabled)

2. **Environment Variable Updates**
   - Removed model-specific environment variables:
     - `NEXT_PUBLIC_OLLAMA_MODEL`
     - `NEXT_PUBLIC_OLLAMA_TOOL_CALL_MODEL`
     - `NEXT_PUBLIC_AZURE_DEPLOYMENT_NAME`
     - `NEXT_PUBLIC_OPENAI_COMPATIBLE_MODEL`
   - Renamed environment variable:
     - `NEXT_PUBLIC_ENABLE_SAVE_CHAT_HISTORY` → `ENABLE_SAVE_CHAT_HISTORY`

#### Development Mode
Edit `public/config/models.json` directly with your model configurations:

```json
{
  "models": [
    {
      "id": "model-id",
      "name": "Model Name",
      "provider": "Provider Name",
      "providerId": "provider-id",
      "enabled": true,
      "toolCallType": "native|manual",
      "toolCallModel": "tool-call-model-id" // only if toolCallType is "manual"
    }
  ]
}
```

##### Using Prebuilt Image
When using the prebuilt image (`ghcr.io/miurla/morphic:latest`), create a `models.json` file alongside your `.env.local` and update your docker-compose.yml to mount it:

```yaml
services:
  morphic:
    image: ghcr.io/miurla/morphic:latest
    env_file: .env.local
    volumes:
      - ./models.json:/app/public/config/models.json
```

##### Building Your Own Image
When building your own Docker image from source:
1. Clone the repository
2. Edit `public/config/models.json` directly with your configurations
3. Build and run the image using docker-compose

### 2. Update Environment Variables
1. Remove the following variables from your .env.local:
   - `NEXT_PUBLIC_OLLAMA_MODEL`
   - `NEXT_PUBLIC_OLLAMA_TOOL_CALL_MODEL`
   - `NEXT_PUBLIC_AZURE_DEPLOYMENT_NAME`
   - `NEXT_PUBLIC_OPENAI_COMPATIBLE_MODEL`
2. If you are using chat history storage, rename:
   - `NEXT_PUBLIC_ENABLE_SAVE_CHAT_HISTORY` to `ENABLE_SAVE_CHAT_HISTORY`

#### Documentation
For detailed configuration instructions, please refer to:
- [Configuration Guide](https://github.com/miurla/morphic/blob/main/docs/CONFIGURATION.md)
- Example configuration in [.env.local.example](https://github.com/miurla/morphic/blob/main/.env.local.example)

#### Migration Guide
1. **For Development**: Edit `public/config/models.json` directly with your model settings
   **For Docker**: Create `models.json` alongside `.env.local` with your model settings
2. Update your `.env.local` by removing the deprecated variables
3. If using chat history, rename the environment variable
4. Restart your development server or Docker container

Please report any issues you encounter during the migration.

**Comment by arsaboo** [comment]
Thanks...we should add an example of a provider like OpenRouter that just requires changing the baseURL in the model.json file.

**Comment by arsaboo** [comment]
I added the following in models.json:
```
    {
      "id": "qwen2.5:latest",
      "name": "Qwen 2.5",
      "provider": "Ollama",
      "providerId": "ollama",
      "enabled": true,
      "toolCallType": "manual",
      "toolCallModel": "phi4"
    },

```

But I still don't see it in the UI. `deepseek-r1` is now working with Ollama.

**Comment by arsaboo** [comment]
Also, this openrouter config did not work:

```yaml
    {
      "id": "openai/o3-mini",
      "name": "O3 Mini",
      "provider": "OpenAI Compatible",
      "providerId": "openai-compatible",
      "enabled": true,
      "toolCallType": "native"
    }
```

I just see `Undefined` in the UI:

![Image](https://github.com/user-attachments/assets/59fee28c-9062-4119-b03a-8e9af6849676)

I do have the following defined in my .env
```yaml
OPENAI_COMPATIBLE_API_KEY=REDACTED
OPENAI_COMPATIBLE_API_BASE_URL="https://openrouter.ai/api/v1"
```

**Comment by niji-vlebiannic** [comment]
@miurla Is it intended that `NEXT_PUBLIC_OPENAI_COMPATIBLE_MODEL` is still checked there?

https://github.com/miurla/morphic/blob/main/lib/utils/registry.ts#L113

**Comment by arsaboo** [comment]
@miurla Just tried. Here's my docker compose:

```yaml
name: morphic-stack
services:
  morphic:
    image: ghcr.io/arsaboo/morphic:latest
    command: bun start -H 0.0.0.0
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - morphic:builder
        - morphic:latest
    env_file: .env
    ports:
      - "3011:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    volumes:
      - ./models.json:/app/public/config/models.json

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - /Users/asaboo/Documents/Containers/morphic/data:/data
    command: redis-server --appendonly yes
```

I do have models.json (with both qwen2.5 and openai/o3-mini configured alongside my .env file. However, I still only see `Deeseek R1` in Ollama models and `Undefined` in OpenAI compatible models. Deepseek R1 on Ollama is working for me, suggesting that the configuration is fine. 

![Image](https://github.com/user-attachments/assets/5a392097-fea8-41af-887f-3b17feecf19a)
