### ISSUE TITLE
[BUG] Failed to load models despite models.json being present

### ISSUE THREAD

**Issue by Expro** [miurla/morphic#469]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Vercel Runtime Logs

- [ ] I have checked the Vercel Runtime Logs for errors (if applicable)

### Current Behavior

I'm getting following error (logs):

   - Local:        http://localhost:3000
   - Network:      http://0.0.0.0:3000

 ✓ Starting...
 ✓ Ready in 636ms
Failed to load models: [Error: Unable to connect. Is the computer able to access the url?] {
  code: 'ConnectionRefused',
  path: 'https://0.0.0.0:3000/config/models.json',
  errno: 0
}
Failed to load models: [Error: Unable to connect. Is the computer able to access the url?] {
  code: 'ConnectionRefused',
  path: 'https://0.0.0.0:3000/config/models.json',
  errno: 0
}

Content of /app/public/config/models.json:

```
{
  "models": [
    {
      "id": "llama3.1:8b-instruct-q8_0",
      "name": "LLama 3.1 8B",
      "provider": "Ollama",
      "providerId": "ollama",
      "enabled": true,
      "toolCallType": "manual",
      "toolCallModel": "llama3.1:8b-instruct-q8_0"
    }
  ]
}
```

### Expected Behavior

models.json is loaded correctly

### Steps To Reproduce

Create new instance from prebuild image with models.json created.

### Environment

```markdown
- OS: Fedora 41
- Browser: Firefox
```

**Comment by miurla** [comment]
Based on the error logs, I can see the application is trying to access "https://0.0.0.0:3000/config/models.json" while your local server is running on http protocol. This is likely related to your browser's security settings that might be forcing HTTPS connections.

I'd recommend trying a different browser to see if the issue persists. If it works in another browser, you'll know it's browser-specific security settings causing the problem.

**Comment by Expro** [comment]
Are you suggesting that Morphic uses models.json by asking cusomer's browser to fetch it over HTTP, instead of reading that locally and including info from it while answering initial request?

How do you handle proxy servers then? Because I currently run it on top of Kubernetes with ingress controller providing HTTPS,

**Comment by jcrabapple** [comment]
I've run across this same issue running it behind an nginx proxy. Any solution?

**Comment by miurla** [comment]
I'm investigating this issue. It seems that the application is trying to fetch the models.json file from `https://0.0.0.0:3000/config/models.json` instead of using the local file path. 

The error suggests a connection issue when trying to access the file via URL rather than directly from the filesystem. This could be related to how the application is configured to load the models configuration.

Let me check the codebase to understand how models.json is being loaded and propose a fix.

**Comment by miurla** [comment]
I've identified the root cause and implemented a fix.

## Root Cause

The problem occurred when trying to fetch `models.json` in certain environments:

1. When using `0.0.0.0` address in local development, which can cause connection issues with HTTPS
2. When running behind proxies where URL construction might be incorrect

## Fix

We've implemented a solution in PR #471 (now merged) that:

1. Improves URL construction to work correctly across different environments
2. Adds a fallback mechanism to load models from a default configuration when the fetch fails
3. Adds better error handling and diagnostic logging

## Verification

Could you please verify that this resolves the issue in your environment? Let us know if you encounter any further problems.

**Comment by Expro** [comment]
I will test it, but one question - why not load list of models directly from Ollama, instead of requiring user to list them manually in file that needs to be constantly updated?

**Comment by miurla** [comment]
The model list isn't just for Ollama models - it includes models from various providers. We can't automatically detect all possible models across different providers, which is why we've made it configurable.

Additionally, many models don't support native tool calling, so the configuration allows users to specify tool call settings (like using manual tool calling with a separate model). This flexibility helps support a wide range of use cases and model capabilities.

The configuration approach gives users more control over which models are enabled and how they're configured, rather than automatically loading everything available.

**Comment by arsaboo** [comment]
@miurla with #471, my models.json is no longer working:

```bash
Attempting to fetch models from: http://192.168.2.162:3011/config/models.json
Attempting to fetch models from: http://192.168.2.162:3011/config/models.json
```

I was using:
```yaml
name: morphic-stack
services:
  morphic:
    image: ghcr.io/miurla/morphic:latest
    command: bun start -H 0.0.0.0
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - morphic:builder
        - morphic:latest
    env_file: .env
    ports:
      - "3011:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    volumes:
      - ./models.json:/app/public/config/models.json

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - /Users/asaboo/Documents/Containers/morphic/data:/data
    command: redis-server --appendonly yes
```

But, it isn't working. Looks like the models.json cannot be mounted.

**Comment by miurla** [comment]
@arsaboo I've tested the issue with Docker and was able to successfully load the models.json file. Here's what I found and what you should check:

## Testing Results

I created a test environment with a similar Docker setup to yours:
```yaml
version: '3'
services:
  morphic:
    image: ghcr.io/miurla/morphic:latest
    ports:
      - "3011:3000"
    volumes:
      - ./test-models.json:/app/public/config/models.json
    environment:
      - OPENAI_API_KEY=dummy-key
```

The models.json file was correctly mounted and loaded by the application. I confirmed this by:
1. Checking the file was present in the container
2. Accessing the application in the browser
3. Verifying the model appeared in the model selection dropdown

## Troubleshooting Steps

Based on your logs, it seems the application is trying to fetch models.json but failing. Here are some things to check:

1. **File Permissions**: Make sure your models.json file has the correct permissions (readable by the container)
   ```bash
   chmod 644 models.json
   ```

2. **File Path**: Verify the exact path in your volume mount
   ```bash
   docker exec your-container-name ls -la /app/public/config/
   ```

3. **File Content**: Check if your models.json has valid JSON format
   ```bash
   docker exec your-container-name cat /app/public/config/models.json
   ```

4. **Network Configuration**: The issue might be related to how the application constructs URLs in Docker. Try adding an environment variable to specify the public URL:
   ```yaml
   environment:
     - PUBLIC_URL=http://192.168.2.162:3011
   ```

5. **Container Restart**: Sometimes a clean restart helps
   ```bash
   docker-compose down
   docker-compose up -d
   ```

Let me know if any of these steps help resolve the issue. If not, we can look into more specific debugging.

**Comment by arsaboo** [comment]
@miurla ok, so I updated the models.json to test-models.json (so that we can easily debug) and used the following compose:
```yaml
name: morphic-stack
services:
  morphic:
    image: ghcr.io/miurla/morphic:latest
    env_file: .env
    ports:
      - "3011:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    volumes:
      - ./test-models.json:/app/public/config/models.json

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - /Users/asaboo/Documents/Containers/morphic/data:/data
    command: redis-server --appendonly yes
```

I can confirm that models.json is available inside the container:
```bash
% docker exec morphic-stack-morphic-1 ls -la /app/public/config/
total 12
drwxr-xr-x 2 root root 4096 Mar  6 02:26 .
drwxr-xr-x 5 root root 4096 Mar  6 02:26 ..
-rw-r--r-- 1 root root 4038 Mar  6 14:47 models.json
```

But, it is still not working for me. Here are the logs:
```bash
Attempting to fetch models from: http://192.168.2.162:3011/config/models.json
Attempting to fetch models from: http://192.168.2.162:3011/config/models.json
Attempting to fetch models from: http://192.168.2.162:3011/config/models.json
Attempting to fetch models from: http://192.168.2.162:3011/config/models.json
Successfully loaded default models
Fetch failed, falling back to default models: Unable to connect. Is the computer able to access the url?
Fetch failed, falling back to default models: Unable to connect. Is the computer able to access the url?
Successfully loaded default models
Successfully loaded default models
Fetch failed, falling back to default models: Unable to connect. Is the computer able to access the url?
Fetch failed, falling back to default models: Unable to connect. Is the computer able to access the url?
Successfully loaded default models
```

I can also confirm that my custom models.json is available at http://192.168.2.162:3011/config/models.json and when I run `docker exec morphic-stack-morphic-1 cat /app/public/config/models.json`

**Comment by arsaboo** [comment]
Just as a test, I tested the same docker compose with the last release (ghcr.io/miurla/morphic:4e698b7fc87edbe578893a06d491169dcadb87f4) and everything works fine.

**Comment by miurla** [comment]
@arsaboo I've identified the root cause of your issue and have a solution.

### Root Cause

The problem occurs because of how URL construction works in Docker environments:

1. Inside the container, your app runs on `localhost:3000`
2. But externally, it's accessed via `192.168.2.162:3011`
3. PR #471 improved URL construction using HTTP headers, but in Docker, these headers contain the external URL
4. The container can't access this external URL from inside, causing the fetch to fail

This explains why it worked with the previous version but fails with the latest one.

### Solution

Add the `PUBLIC_URL` environment variable to your Docker Compose file:

```yaml
environment:
  - PUBLIC_URL=http://localhost:3000
```

This tells the application to use the internal container URL when fetching models.json instead of trying to use the external URL from headers.

After making this change, restart your container:

```bash
docker-compose down
docker-compose up -d
```

This should resolve the issue while still benefiting from the improved error handling and fallback mechanisms added in PR #471.

**Comment by arsaboo** [comment]
Indeed, it worked after I set `PUBLIC_URL=http://localhost:3000`. However, it feels hackish.

**Comment by miurla** [comment]
Hi @arsaboo,

This issue has been fixed in PR #472. We've added support for a `BASE_URL` environment variable to help Docker environments correctly load resources like `models.json`.

### Problem
In Docker containers, the application couldn't construct correct URLs for internal resources based on request headers alone.

### Solution
The implementation now:
1. Prioritizes the `BASE_URL` environment variable if set
2. Falls back to header-based URL construction if not available

### Usage
Add the `BASE_URL` environment variable to your Docker Compose:

```yaml
services:
  morphic:
    image: ghcr.io/miurla/morphic:latest
    ports:
      - '3000:3000'
    volumes:
      - ./models.json:/app/public/config/models.json
    environment:
      - BASE_URL=http://localhost:3000
```

Documentation has been added to `.env.local.example` as well.

We've confirmed this works with the latest prebuilt image.

Thanks for reporting this issue.
