### ISSUE TITLE
[BUG] Allow Setting `apiVersion` in `models.json` for Azure OpenAI (Default `2024-10-01-preview` Too Old for New Models)

### ISSUE THREAD

**Issue by fabsau** [miurla/morphic#498]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Vercel Runtime Logs

- [ ] I have checked the Vercel Runtime Logs for errors (if applicable)

### Current Behavior

**Describe the problem**

The AI SDK used by Morphic currently defaults to Azure OpenAI API version `2024-10-01-preview`:

However, this version is now too old to support some of the newer models, such as `o3-mini`. When attempting to use these models, the following error occurs:

```
Error in chat: Model {modelName} is enabled only for api versions 2024-12-01-preview and later
```

The latest available API version is `2025-03-01-preview`, but there is currently no way to override the `apiVersion` via `models.json`. This prevents access to the latest models and features.

### Expected Behavior

Allow users to set the `apiVersion` (e.g., `2025-03-01-preview`) for Azure OpenAI models directly in `models.json`, so newer models like o3-mini work.

### Steps To Reproduce

Try o3-mini in AzureOpenAI

### Environment

```markdown
- OS:
- Browser:
```

### Anything else?

**Thank you!**

**Comment by miurla** [comment]
I've fixed this issue in PR [#503](https://github.com/miurla/morphic/pull/503) which has been merged.

## What was done
I updated the Azure OpenAI API version from the default `2024-10-01-preview` to `2025-03-01-preview` in the Azure provider initialization code.

```typescript
azure: createAzure({
  apiKey: process.env.AZURE_API_KEY,
  resourceName: process.env.AZURE_RESOURCE_NAME,
  apiVersion: "2025-03-01-preview"
}),
```

## Why we didn't modify the config/models.json
I chose to update the API version directly in the SDK initialization instead of adding it to the models.json configuration for these reasons:

1. **Simplicity**: A single change at the provider level applies to all Azure OpenAI models, requiring no per-model configuration
2. **Consistency**: Ensures all models use the same API version, preventing potential compatibility issues
3. **Architecture alignment**: The API version is a provider-level setting in the AI SDK architecture, not a model-specific configuration
4. **Future-proofing**: When Azure updates their API versions in the future, we can update in one place rather than requiring users to update each model definition

This approach provides a cleaner solution while enabling all new Azure OpenAI models (including o3-mini) to work properly.

The issue should now be resolved. Please confirm if you are able to use newer models like o3-mini with this change.

**Comment by fabsau** [comment]
@miurla Thank you for fixing it this fast!!! Unfortunately I am still getting erros. For o4-mini I am getting this error:
`Error in chat: Unsupported value: 'temperature' does not support 0 with this model. Only the default (1) value is supported.`


And for o3-mini:
`Error in chat: Invalid schema for function 'search': In context=(), 'required' is required to be supplied and to be an array including every key in properties. Missing 'max_results'.`

GPT-4.1 is working flawlessly.

Here my morphic.env.j2 (ansible template):
```
ENABLE_SAVE_CHAT_HISTORY=true
USE_LOCAL_REDIS=true
LOCAL_REDIS_URL=redis://morphic-redis:6379
AZURE_API_KEY={{ OPENAI_AZURE_API_KEY_1 }}
AZURE_RESOURCE_NAME={{ OPENAI_AZURE_INSTANCENAME_1 }}
SEARCH_API=searxng
SEARXNG_API_URL=https://{{ endpoints.searxng.dmz }}
SEARXNG_IMAGE_PROXY=false
SEARXNG_LIMITER=false
SEARXNG_DEFAULT_DEPTH=advanced
SEARXNG_MAX_RESULTS=50
SEARXNG_SAFESEARCH=0
NEXT_PUBLIC_ENABLE_SHARE=true
```

My morphic-models.json.j2:
```
{
  "models": [
    {
      "id": "o4-mini",
      "name": "o4-mini",
      "provider": "Azure",
      "providerId": "azure",
      "enabled": true,
      "toolCallType": "native"
    },
    {
      "id": "o3-mini",
      "name": "o3-mini",
      "provider": "Azure",
      "providerId": "azure",
      "enabled": true,
      "toolCallType": "native"
    },
    {
      "id": "gpt-4.1",
      "name": "gpt-4.1",
      "provider": "Azure",
      "providerId": "azure",
      "enabled": true,
      "toolCallType": "native"
    },
    {
      "id": "gpt-4.1-mini",
      "name": "gpt-4.1-mini",
      "provider": "Azure",
      "providerId": "azure",
      "enabled": true,
      "toolCallType": "native"
    },
    {
      "id": "gpt-4.1-nano",
      "name": "gpt-4.1-nano",
      "provider": "Azure",
      "providerId": "azure",
      "enabled": true,
      "toolCallType": "native"
    }
  ]
}

```
And finally my docker-compose.yml:
```
  morphic:
    image: ghcr.io/miurla/morphic:latest
    container_name: morphic
    hostname: morphic
    restart: unless-stopped
    command:
      bun start -H 0.0.0.0
    security_opt:
      - no-new-privileges
    env_file:
      - ./morphic.env
    networks:
      - morphic
    volumes:
      - ./config/morphic-models.json:/app/public/config/models.json

### MORPHIC-REDIS ###
  morphic-redis:
    image: redis:alpine
    container_name: morphic-redis
    hostname: morphic-redis
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    env_file:
      - ../common.env
    networks:
      - morphic
    volumes:
      - ./morphic/data/redis:/data
```

I also repulled the docker image, so i should be running the latest version.
