### ISSUE TITLE
Could you please provide a Docker Compose YAML file? 

### ISSUE THREAD

**Issue by GuGuGee** [miurla/morphic#78]
I want to deploy it on my own server. Thanks！

**Comment by andrewginns** [comment]
I've done something like this in my fork. Allows for the UI to be accessed via my NordVPN mesh network, hopefully it's helpful to you! https://github.com/andrewginns/morphic

**Comment by arsaboo** [comment]
@andrewginns can you also provide a simple compose file without Nord?

**Comment by arsaboo** [comment]
@miurla I understand you have the dockerfile, but it will be great if you can provide a compose file for folks to get started...thanks!

**Comment by arsaboo** [comment]
Here's one that works:
```yaml
version: "3.7"
services:
  morphic:
    build:
      context: .
      dockerfile: Dockerfile
    command: bun dev
    env_file: .env
    ports:
      - "3008:3000"
```

If you want to access it on the entire network,  change the command too `bun dev -H 0.0.0.0`

**Comment by andrewginns** [comment]
I added a generic `docker-compose.yaml` file in a PR here https://github.com/miurla/morphic/pull/131#issue-2289434476
```
# This is a Docker Compose file for setting up the morphic-stack environment.

name: morphic-stack
services:
  morphic:
    build:
      context: . # The build context is the current directory
      dockerfile: Dockerfile
    command: bun dev # Use `bun dev -H 0.0.0.0` to listen on all interfaces
    env_file: .env.local # Load environment variables
    ports:
      - "3000:3000" # Maps port 3000 on the host to port 3000 in the container.
```
